### ISSUE TITLE
True buffer local control of NeoCodeium

### ISSUE THREAD

**Issue by mehalter** [monkoose/neocodeium#27]
### Problem

Currently the semantics of "globally enabled" and "buffer local enabled" are a bit blurred and mixed. It seems that the to use the buffer local enabling then NeoCodeium must be globally enabled. This means that there is no way to use this plugin in a way where you only enable NeoCodeium on a per-buffer basis.

if I use `enabled = false` on startup and then `:NeoCodeium enable_buffer` does not do anything because the server is not globally available.

I also tried doing `enabled = function() return false end` which gets closer but now it is blocked by `enabled` function

I got pretty close to a normal behavior that is similar to other vim global/local options by doing `enabled = function(bufnr) return vim.F.if_nil(vim.b[bufnr].neocodeium_enabled, vim.g.neocodeium_enabled) end`. This actually works perfectly for buffer local control but completely breaks the global toggling. This seems expose that there is a bug where if you are using `enabled` as a function then if you do the global toggling such as `:NeoCodeium enable`/`:NeoCodeium disable`/`:NeoCodeium toggle` then it completely stops using the `enabled` function because the global variable will always take precedence once it is set.

### Expected behavior

There should be a clear understanding of when NeoCodeium is "enabled" or "disabled" and it seems like the current implementation gets into confused states very easily. Especially where `:NeoCodeium toggle` completely  breaks the `enabled` function all together.

With this, it would also be nice to be able to have true buffer local control over NeoCodeium being enabled rather than just having buffer local disabling when the entire thing is globally enabled.

**Comment by monkoose** [comment]
> This means that there is no way to use this plugin in a way where you only enable NeoCodeium on a per-buffer basis.

Wrong. I specifically add the feature of enabled as function, so you can do whatever you want with it.
So for your example nothing stops you to add
```lua
enabled = function(buf)
    local ok, v = pcall(vim.api.nvim_buf_get_var, buf, "whatever_name_you_want")
    if ok and v then
        true
    end
    return false
end
```
Then just implement logic to add/remove/toggle this var name to the buffer with hotkey on any event or with command.

As of the logic that is currently supported by the plugin, it was made in mind that users would likely to have it enabled, and just disable in some specific buffers, not because of privacy concerns, but more like if for current buffer session this suggestions are annoying. Or they would like to completely disable plugin lets say for some time (pairing programming - less noise etc), and they definitely don't want to at the same time be surprised that some buffer has enabled variable and then disable it for each buffer where it is enabled.

**Comment by mehalter** [comment]
This is true where you can add all of your own logic for toggling and create your own functions for toggling and your own status functions. At that point it really seems like the user is just re-implementing the plugin for what seems like a logical use of enabling/disabling that may leave users confused as to why it doesn't work out of the box. Especially because if they do this then they will be force to not use the built in `:Neocodeium` commands for `enable`/`disable`/`toggle` because they need the enabled to be always on to guarantee that it gets to the function in the first place to reach their control of the plugin.

**Comment by monkoose** [comment]
I'm the user of my plugin, users before you never complained about this "confusion".
Personally I would be surprised and confused if it would act as you described. And for minority (and I believe users who want the plugin act as you described) there is this solution.

Or what is your solution for the behavior that I want?

**Comment by mehalter** [comment]
Isn't the behavior that you want supported by the code implemented in #28 ? If you only do the buffer toggling when the plugin is enabled globally then it disables the buffer which is the behavior you are looking for right?

Also with the given code that you sent, this will only work if the plugin is fully enabled and then I would not be able to use the buffer toggle and global toggles in the plugin. It also means I can no longer use the `get_status` function and the user must also implement and maintain their own

**Comment by monkoose** [comment]
@mehalter, my apologize.

I have this featissue (because sometimes it is a feature, but sometimes it is an issue), that when I reading something and in my head thinking that I already have fully grasped the full picture (what is more often than I want is wrong) I continue to process leftover information by skipping some parts of the text, reading by diagonal (or even fully skipping chunks of text). I understand that this bites and sometimes even hard (especially when I'm reading in English and to fully understand the text it sometimes require a translation of some words (even though I think my vocabulary is decent, unlike grammar), but I'm lazily skip this words), but it is the way of me to faster process the information. And I do believe most people do this, but someone just master it better then I'm and wrong in much lesser situations. So I have reread your post, and I completely agree with you. I now understand how you have felt having in your head clear vision that you are right trying to break the wall which i built. 

So currently we have this precedence checking if completion should work:
wrong encoding > global variable > filter function (which i currently also issue of combining with enabled option) > filetypes > buffer variable

What precedence should be for enabling state:
1. wrong encoding (no matter what there is no point to send something to the server if it will reject it. But I haven't personally test if the server really rejects wrong encoding (and grabbed this as stated from codeium.vim). Should we test this?
2. options.enabled
3. buffer variable
4/5. Seems like they are irrelevant options.filter() and options.filetypes

You do agree?

**Comment by mehalter** [comment]
Thanks for giving this another re-read and responding. I appreciate you taking the time to consider it 😊 

I think the only difference in what I would expect is that buffer local priority would be above the global setting. This is like the setting specified with the smallest scope should have the highest priority because it is the most specific ask by the user. If that makes sense. The global state should be basically the "current default" when opening new buffers and the state for buffers that have not been singled out by the user with buffer specific toggling. Once a specific buffer is toggled/enabled/disabled by the user, that should take the highest priority because it was singled out by the user.

**Comment by mehalter** [comment]
I think the PR I opened with my recommendation is pretty much what you described with the small caveat that I added above. It might be an interesting thing to take a look at and test a bit to see what you think of the behavior :)

**Comment by monkoose** [comment]
In my head global to buffer precedence is taken from electrical panel. If you turn off main switch, no matter what state of the switches for specific rooms it should be always off. I still think this is the right thing to do, especially if disabled at startup options.enabled doesn't start the server. And we would have filter function independent of it, so users who really want to achieve your behavior have a workaround.

Also I think something like `:NeoCodeium! disable` and `require('neocodeium.commands').disable(true)` should stop the server too, for the users like you who wants to stop the server. Also I do believe I have TODO somewhere to also remove unwanted (maybe even all) autocmds on toggling global enabled option.

**Comment by mehalter** [comment]
The main thing is with this "master toggle" it really removes the ability for the buffer local toggles to have much meaning. Like it is quite important in my mind that if I run something like "buffer enable" then that should _always_ work. That's me saying _i want this buffer to be enabled_. With the current model that isn't true. I just like that when I used a command then it is respected. I'm also coming from 25 years of using vi/vim so I definitely have a very specific view of how local/global variables and options are interpreted that this just goes against 😅 also totally understandable if you want to pave your own way

**Comment by monkoose** [comment]
I too have like more than 20 years of vim experience, I just think that vim logic of global and local should not apply here. Especially if I will add stopping the server feature to `:NeoCodeium disable`, there is no way to "enable" the server only for a buffer.  

It also would require to start the server on `:Neocodeium enable_buffer` which I don't want to do either, and then if you would run `:NeoCodeium! disable` with stopping the server, your "enabled" buffers even if we swap global - local precedence would still not work. So its counter intuitive. And if you check `copilot.vim` and `codeium.vim` I do believe they behave the same.

**Comment by mehalter** [comment]
Alright I'll leave the decision up to you :) I don't have a strong enough opinion nor experience with the internals. Sorry for all the noise here!

**Comment by monkoose** [comment]
Ok, I'm closing this as not planned.
